/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.github.slashmili.Zendroid;

public final class R {
    public static final class array {
        public static final int update_every=0x7f060000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int severity=0x7f020000;
        public static final int severity3=0x7f020001;
        public static final int severity3_background=0x7f020002;
        public static final int severity3_background_noevent=0x7f020003;
        public static final int severity4=0x7f020004;
        public static final int severity4_background=0x7f020005;
        public static final int severity4_background_noevent=0x7f020006;
        public static final int severity5=0x7f020007;
        public static final int severity5_background=0x7f020008;
        public static final int severity5_background_noevent=0x7f020009;
        public static final int small_widget_error_background=0x7f02000a;
    }
    public static final class id {
        public static final int WidgetBox=0x7f070007;
        public static final int WidgetErrorBox=0x7f070011;
        public static final int cancel=0x7f070005;
        public static final int cancel_button=0x7f070018;
        public static final int every=0x7f070003;
        public static final int ok=0x7f070006;
        public static final int ok_button=0x7f070019;
        public static final int password=0x7f070002;
        public static final int severity3=0x7f070010;
        public static final int severity3Box=0x7f07000e;
        public static final int severity3Img=0x7f07000f;
        public static final int severity4=0x7f07000d;
        public static final int severity4Box=0x7f07000b;
        public static final int severity4Img=0x7f07000c;
        public static final int severity5=0x7f07000a;
        public static final int severity5Box=0x7f070008;
        public static final int severity5Img=0x7f070009;
        public static final int url=0x7f070000;
        public static final int username=0x7f070001;
        public static final int widget149=0x7f070004;
        public static final int widgetError=0x7f070012;
        public static final int widgetconf_match=0x7f070017;
        public static final int widgetconf_pass=0x7f070015;
        public static final int widgetconf_update=0x7f070016;
        public static final int widgetconf_url=0x7f070013;
        public static final int widgetconf_user=0x7f070014;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int small_widget=0x7f030001;
        public static final int small_widget_error=0x7f030002;
        public static final int widget_configure=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int small_widget=0x7f040000;
    }
}
