/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.github.slashmili.Zendroid;

public final class R {
    public static final class array {
        public static final int on_event_choice=0x7f050000;
        public static final int update_every=0x7f050002;
        public static final int update_every_choice=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int buy_me_beer=0x7f020000;
        public static final int severity=0x7f020001;
        public static final int severity3=0x7f020002;
        public static final int severity3_background=0x7f020003;
        public static final int severity3_background_noevent=0x7f020004;
        public static final int severity3_notify=0x7f020005;
        public static final int severity4=0x7f020006;
        public static final int severity4_background=0x7f020007;
        public static final int severity4_background_noevent=0x7f020008;
        public static final int severity4_notify=0x7f020009;
        public static final int severity5=0x7f02000a;
        public static final int severity5_background=0x7f02000b;
        public static final int severity5_background_noevent=0x7f02000c;
        public static final int severity5_notify=0x7f02000d;
        public static final int small_widget_error_background=0x7f02000e;
        public static final int zendroid_icon=0x7f02000f;
    }
    public static final class id {
        public static final int WidgetBox=0x7f080024;
        public static final int WidgetErrorBox=0x7f08002e;
        public static final int btnGetLastStatus=0x7f080021;
        public static final int btnSaveSettings=0x7f080020;
        public static final int chkInvalidSSL=0x7f08001e;
        public static final int editText4=0x7f08000c;
        public static final int mnuAbout=0x7f080032;
        public static final int mnuLastStatus=0x7f080030;
        public static final int mnuRemoveAccount=0x7f080031;
        public static final int ok=0x7f080022;
        public static final int severity3=0x7f08002d;
        public static final int severity3Box=0x7f08002b;
        public static final int severity3Img=0x7f08002c;
        public static final int severity4=0x7f08002a;
        public static final int severity4Box=0x7f080028;
        public static final int severity4Img=0x7f080029;
        public static final int severity5=0x7f080027;
        public static final int severity5Box=0x7f080025;
        public static final int severity5Img=0x7f080026;
        public static final int spnOnCritical=0x7f08000f;
        public static final int spnOnError=0x7f080012;
        public static final int spnOnWarning=0x7f080015;
        public static final int spnUpdateEvery=0x7f080018;
        public static final int tableLayout1=0x7f080000;
        public static final int tableRow1=0x7f080001;
        public static final int tableRow10=0x7f080019;
        public static final int tableRow11=0x7f08001f;
        public static final int tableRow12=0x7f08001c;
        public static final int tableRow2=0x7f080004;
        public static final int tableRow3=0x7f080007;
        public static final int tableRow4=0x7f08000a;
        public static final int tableRow5=0x7f08000d;
        public static final int tableRow7=0x7f080010;
        public static final int tableRow8=0x7f080013;
        public static final int tableRow9=0x7f080016;
        public static final int textView1=0x7f080002;
        public static final int textView11=0x7f08001d;
        public static final int textView2=0x7f080005;
        public static final int textView3=0x7f080008;
        public static final int textView4=0x7f08000b;
        public static final int textView5=0x7f08000e;
        public static final int textView6=0x7f080011;
        public static final int textView7=0x7f080014;
        public static final int textView8=0x7f080017;
        public static final int textView9=0x7f08001a;
        public static final int txtMatchDevice=0x7f08001b;
        public static final int txtZenossPass=0x7f080009;
        public static final int txtZenossURL=0x7f080003;
        public static final int txtZenossUser=0x7f080006;
        public static final int widgetError=0x7f08002f;
        public static final int widgetHolder=0x7f080023;
    }
    public static final class layout {
        public static final int global_configuration=0x7f030000;
        public static final int main=0x7f030001;
        public static final int small_widget=0x7f030002;
        public static final int small_widget_error=0x7f030003;
    }
    public static final class menu {
        public static final int config_menu=0x7f070000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
    }
    public static final class xml {
        public static final int small_widget=0x7f040000;
    }
}
